# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-05 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20150619_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoRuns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runid', models.CharField(db_index=True, max_length=240)),
            ],
        ),
    ]
