::Tool script. put yer stuff here
::receives some env vars like %CWD%, %TMPFILE% from the form
::The script is run in $CWD, which is autocreated by the node on startup
::----------------------------------------------------------------------

::clone directly into current working directory '.':
git clone git@github.com:psrc/model-dashboard.git .

::switch to git tag if defined
if defined TAG git checkout %TAG%

::then copy input_configuration.py if it exists
if defined TMPFILE move /Y "%TMPFILE%" .

:: run the model
echo "SCHATZI!" > biggles.txt
