@echo off

:: Tool script. Put yer stuff here
:: Receives some env vars like %CWD%, %TMPFILE% from the form
:: The script is run in %CWD%, which is autocreated by the node on startup
:: ----------------------------------------------------------------------

git clone https://github.com/psrc/model-dashboard.git
if ERRORLEVEL 1 exit

cd soundcast

if defined TAG git checkout %TAG%
if ERRORLEVEL 1 exit

if defined TMPFILE move /Y "%TMPFILE%" .

@echo 'made it! freezing inputs"
call ..\soundcast-freezer.bat

@echo 'made it! running soundcast.'
python run_soundcast.py
