@echo on

:: Tool script. Put yer stuff here
:: Receives some env vars like %CWD%, %TMPFILE% from the form
:: The script is run in %CWD%, which is autocreated by the node on startup
:: ----------------------------------------------------------------------

git clone https://github.com/psrc/luv.git
if ERRORLEVEL 1 exit

cd .\luv\QC

if defined TAG git checkout %TAG%
if ERRORLEVEL 1 exit

if defined TMPFILE move /Y "%TMPFILE%" .

:: write new inputs.txt file
(
	echo test=%QC_RUN1%
	echo QC_NAME=run81
	echo QC_BASE_DIRECTORY=//modelsrv3/e$$/opusgit/urbansim_data/data/psrc_parcel/runs
	echo QC_RUN1=run_81.run_2016_07_05_16_00
	echo QC_RUN2=run_170.run_2015_09_15_16_02
	echo DECREASE_THRESHOLD=100
	echo DECREASE_THRESHOLD_PERCENT=2
	echo RREPORT_RUNS=run_78.run_2016_06_23_09_47, run_170.run_2015_09_15_16_02
echo RREPORT_ANNUAL=TRUE
) > inputs.txt

:: freeze inputs.
:: note - Queue copies the freezer batch file to '..\snapshot.bat', no
:: matter what it's called in the plugin folder.

echo ** made it! freezing inputs.
call ..\snapshot.bat

:: run R summary scripts
make clean
make all